import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user.isSignedIn ? (
          <div className="text-white">
            <h1 className="text-4xl font-bold">Welcome!</h1>
            <p className="text-xl">You are signed in with Clerk.</p>
            <SignOutButton />
          </div>
        ) : (
          <div className="text-white">
            <h1 className="text-4xl font-bold">Welcome!</h1>
            <p className="text-xl">You are not signed in.</p>
            <SignInButton />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
